### ISSUE TITLE
EVERYTIME FRIEND ...

### ISSUE THREAD

**Issue by lllilllilllilili** [brotherspear1994/TIL#1]
안녕하세요 

신한이 떠서 연락 드리고 싶었는데 어디로 연락 드릴지 몰라 이슈 열어보았습니다..

기분이 상하셨으면 죄송합니다..

시간 내주셔서 정말 감사드려요!

**Comment by brotherspear1994** [comment]
헐 맞다! 제가 구글 이메일을 확인 잘 못해서 지금봤네요 ㅜㅜ 이미 자소서 작성 하셨나요 ????

2021년 9월 7일 (화) 오후 7:05, 고슴도치짱 ***@***.***>님이 작성:

**Comment by lllilllilllilili** [comment]
오 수일내로 작성해서 검토 요청드려도 될까요????!!! 

메일 하나만 남겨주시면 감사하겠습니다. @_@
